name: Lint and Test
on:
  workflow_call

permissions:
  id-token: write
  contents: read

jobs:
  lint_and_test:
    name: "Lint and Test Python Code"
    runs-on: [self-hosted, Linux, X64, adp]
    continue-on-error: true
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint

      - name: Run linter
        run: pylint **/*.py